### ISSUE TITLE
H4X-Tools doesn't run after building it (Caused by twitter_scrape)

### ISSUE THREAD

**Issue by V1li** [V1li/H4X-Tools#7]
After running `setup.sh` and typing `h4xtools` in terminal, it gives the following:

```
Traceback (most recent call last):
  File "h4xtools.py", line 25, in <module>
    from utils import email_search, search_username, ig_scrape, whois_lookup, webhook_spammer, ip_scanner, ip_lookup, \
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "utils/twitter_scraping.py", line 18, in <module>
    import snscrape.modules.twitter as snstwitter
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "snscrape/modules/__init__.py", line 17, in <module>
  File "snscrape/modules/__init__.py", line 13, in _import_modules
AttributeError: 'FrozenImporter' object has no attribute 'find_module'. Did you mean: 'exec_module'?
[380003] Failed to execute script 'h4xtools' due to unhandled exception!
```

H4X-Tools can be run normally tho using `python3 h4xtools.py`

**Comment by V1li** [comment]
Yep, after reading the issues for snscrape (https://github.com/JustAnotherArchivist/snscrape/issues/846), I guess its best to just remove the whole twitter scrape tool.

**Comment by itsMyrto** [comment]
Twitter announced that it would no longer allow any developer to use its APIs. I found out a few months after i contributed. If i knew that earlier i would probably scrape another social media. Anyways, I dont think you should keep something that doesn't work anymore and i really don't mind if you remove it. Another solution could be to remove it from the main branch and create a second branch to put it there just in case it works again in the future. But honestly, do what you feel its better for your project !

**Comment by V1li** [comment]
Thanks for the reply, but yeah. Ima remove it for now and maybe replace it with something else? Since snscrape works with reddit and mastodon for example. If you want to help with it, feel free to contribute again!

Closing this issue now.
